[SVR-6] Refresh 토큰 rotate 구현
DCNJ-Uket/Uket-BE pull request #17
Opened 2024-05-13 20:11 UTC by sam971114

# 📌 개요
- Refresh 토큰 rotate 구현을 완료해두었습니다.
- Refresh 토큰에서 userId정보를 빼고, redis의 key값으로 활용해 accessToken과 userId를 저장해두었습니다.
- 저장된 key값은 key값들을 구분하기 위해 refreshToken:${value}와 같은 형식으로 구현되어있습니다.

# 💻 작업사항
- [x] Redis에 토큰 저장 로직 추가
- [x] Token Reissue 진행할경우 Redis에서 기존 토큰 삭제 후 재발급 로직 추가

# ❌ 주의사항
- TestCode에서 redis의 유효기간이 지난후에 확실히 삭제되는지 확인하기 위해 TokenService.java의 expire구문의 유효시간을 2초로 변경 후 test 진행하여야합니다. 해당 내용 관련해 문의 부탁드립니다.

# 💡 코드 리뷰 요청사항
- Redis에 저장이 똑바로 되는지 확인 부탁드립니다.
- 유효기간이 지난후에 Redis에서 삭제가 되는지 확인 부탁드립니다.
- Reissue를 진행할경우 기존의 토큰과 새롭게 발급되어 redis에 저장된 토큰이 다른지 확인 부탁드립니다.

2024-05-14 01:09 UTC, 0703kyj requested changes, later dismissed
고생하셨습니다~ 확인할 부분 있어서 코멘트 남겨요!
그 테스트가 실패한 것 같습니다..! 수정 부탁드릴게요~

2024-05-14 01:09 UTC, 0703kyj commented on application/ticket-app-api/build.gradle
> +
여기에 redis 의존성이 필요한건가요?

2024-05-14 01:09 UTC, 0703kyj commented on application/ticket-app-api/src/main/java/com/uket/app/ticket/api/controller/impl/DevController.java
> +        String newRefreshToken = jwtAuthTokenUtil.createRefreshToken( 7_200_000L);
여기서 expiration을 따로 지정해주신 이유가 궁금해요!

2024-05-14 01:09 UTC, 0703kyj commented on application/ticket-app-api/src/main/java/com/uket/app/ticket/api/service/AuthService.java
> +        tokenService.checkAndDeleteTokens(refreshToken);
함수명에 And를 넣는 것은 불가피한 경우를 제외하고 지양해야하는 패턴으로 알고 있어요! 함수 역할을 보니까 값이 존재하는 경우 값을 지우는 함수인 것 같은데 그냥 deleteToken으로 하거나 deleteTokenIfExist 정도가 적당해 보입니다 :)

2024-05-14 01:09 UTC, 0703kyj commented on application/ticket-app-api/src/main/resources/application.yml
> +      port: 6379
지금 서버에 redis가 안띄어져 있을거라 이거 설정하고 합쳐야할 듯 합니당

2024-05-14 01:09 UTC, 0703kyj commented on application/ticket-app-api/src/test/java/com/uket/app/ticket/api/service/TokenServiceTest.java
> +        Set<String> keys = tokenService.allKeys();
redis에서 keys 명령어는 실무 환경에서 성능저하때문에 사용하면 안되는 명령어라고 합니다! 이유는 한 번 찾아보시면 좋을 것 같아요 :) 그래서 tokenService에 해당 명령어를 사용할 수 있는 함수는 제거하고 만약 테스트코드에서 꼭 사용해야한다면 redisTemplete으로 바로 사용하는 편이 좋을 것 같습니당.

2024-05-14 01:09 UTC, 0703kyj commented on application/ticket-app-api/src/test/java/com/uket/app/ticket/api/service/TokenServiceTest.java
> +        Thread.sleep(3000);
테스트코드는 코드 수정 없이 항상 통과되는 환경으로 작성 부탁드려요..!

2024-05-14 01:09 UTC, 0703kyj commented on domain/core-domain/src/main/generated/com/uket/domain/core/entity/QBaseEntity.java
QType들은 합쳐지면 안됩니다..! generated 폴더가 build 폴더 밑에서 생성되야 될텐데 왜 이렇게 됐는지 모르겠네요..? 한 번 확인 부탁드립니다~

2024-05-14 01:09 UTC, 0703kyj commented on modules/jwt-provider/src/main/java/com/uket/modules/jwt/util/JwtAuthTokenUtil.java
> +                .claim(JwtValues.JWT_PAYLOAD_KEY_ID, uuid)
이거 key값이 JWT_PAYLOAD_KEY_UUID 있을거에요! 그걸로 변경 부탁드릴게요~

2024-05-14 01:09 UTC, 0703kyj commented on modules/jwt-provider/src/main/java/com/uket/modules/jwt/util/JwtAuthTokenUtil.java
> +                .claim(JwtValues.JWT_PAYLOAD_KEY_ID, uuid)
여기도 key값 변경 부탁드려요~

2024-05-14 01:09 UTC, 0703kyj commented on modules/token-redis/src/main/java/com/uket/modules/redis/config/RedisConfig.java
> +    }
@RequiredArgsConstructor 로 변경하는게 좋아보입니다~

2024-05-14 01:09 UTC, 0703kyj commented on modules/token-redis/src/main/java/com/uket/modules/redis/properties/RedisProperties.java
> +    }
Setter랑 Getter 없애고 이 파일 Class 말고 Record로 변경 부탁드릴게요~

2024-05-14 01:09 UTC, 0703kyj commented on modules/token-redis/src/main/java/com/uket/modules/redis/properties/RedisProperties.java
> +@Configuration
Configuration 필요 없습니당

2024-05-14 01:09 UTC, 0703kyj commented on modules/token-redis/src/main/java/com/uket/modules/redis/service/TokenService.java
> +
공백이 줄이면 좀 더 깔끔할 것 같아요..!

2024-05-14 01:09 UTC, 0703kyj commented on modules/token-redis/src/main/java/com/uket/modules/redis/service/TokenService.java
> +        tokenDetails.put("userId", userId.toString());
문자열은 상수로 처리 부탁드릴게요~

2024-05-14 01:09 UTC, 0703kyj commented on modules/token-redis/src/main/java/com/uket/modules/redis/service/TokenService.java
> +        //redisTemplate.expire(refreshTokenKey, Duration.ofSeconds(2));
아까 테스트 코드때문에 주석처리한 것 같은데 없애고 테스트코드를 수정하는 방향으로 가는게 좋아보여요ㅎㅎ

2024-05-14 01:09 UTC, 0703kyj commented on modules/token-redis/src/main/java/com/uket/modules/redis/service/TokenService.java
> +    }
keys는 되도록 사용하지 않는 편이 좋다고 합니다!

2024-05-14 01:09 UTC, 0703kyj commented on modules/token-redis/src/main/java/com/uket/modules/redis/service/TokenService.java
> +            throw new IllegalStateException("Refresh token is invalid or expired");
Custom 예외 처리 부탁드릴게요~

2024-05-14 01:09 UTC, 0703kyj commented on modules/token-redis/src/main/java/com/uket/modules/redis/service/TokenService.java
> +    }
refreshToken에 해당하는 AccessToken이 맞는지 확인하는 로직이 빠져서 해당 함수가 사용되지 않은 것 같습니다~ 확인 부탁드려요!

2024-05-14 01:09 UTC, 0703kyj commented on modules/token-redis/src/main/java/com/uket/modules/redis/service/TokenService.java
> +
null이면 null로 리턴하는 것보다 Optional으로 감싸서 추후 empty인 경우 처리하게 하던가 아니면 예외를 발생시키는 편이 좋을 것 같습니다. 아래 AccessToken 가져오는 로직에서도 마찬가지로 처리 부탁드려요~

2024-05-14 01:09 UTC, 0703kyj commented on modules/token-redis/src/main/java/com/uket/modules/redis/dto/RefreshTokenResponse.java
> +}
Dto 클래스는 모두 Record로 부탁드립니다!

2024-05-14 01:14 UTC, 0703kyj commented on modules/token-redis/src/main/java/com/uket/modules/redis/properties/RedisProperties.java
> +    private String password;
application.yml에 password 설정된 값이 없는데 어디서 설정하는 건가요?

2024-05-14 01:18 UTC, 0703kyj commented on modules/token-redis/src/main/java/com/uket/modules/redis/config/RedisConfig.java
> +        redisTemplate.setDefaultSerializer(new StringRedisSerializer());
이 설정들은 어디서 사용하나요?

2024-05-14 01:24 UTC, 0703kyj commented on modules/token-redis/src/main/java/com/uket/modules/redis/service/TokenService.java
> +public class TokenService {
저희 서비스가 Auth관련 Token이외에 Ticket관련 Token을 사용하고 있어서 클래스명이 모호해질 수도 있을 것 같아요..!

2024-05-14 01:52 UTC, 0703kyj commented on modules/token-redis/src/main/java/com/uket/modules/redis/service/TokenService.java
> +        }
delete 자체가 실패하면 false를 반환하는 것 같습니다! 그럼 해당 키값이 없었다는 거나 마찬가지니까 굳이 두번 체크할 필요 없어 보여요~

2024-05-14 01:54 UTC, 0703kyj commented on modules/token-redis/src/main/java/com/uket/modules/redis/service/TokenService.java
> +    }
storeToken에서 값이 있는 경우 이미 지우는 것 같은데 해당 메서드를 private로 바꾸고 storeToken에서 호출하는 방식으로 바꾸는게 좋은 것 같습니다. 외부에서 한번 더 호출할 필요가 없어보여요~

2024-05-15 07:18 UTC, 0703kyj commented on modules/token-redis/src/main/java/com/uket/modules/redis/service/TokenService.java
> +
단순히 null 체크해서 값을 판단하는 건 지금 방식이 더 값이 싼 방법이라고 하네요..! 그런데 여기서는 null인 경우 null을 반환하는데 그러면 추후 `userService.findById()`에서 문제가 생길 것 같아요! 예외를 발생시키는게 좋아보이는데 어떻게 생각하세요?

2024-05-27 02:08 UTC, sam971114 commented on application/ticket-app-api/build.gradle
> +
해당 내용 삭제 진행했습니다.

2024-05-27 02:14 UTC, sam971114 commented on application/ticket-app-api/src/main/java/com/uket/app/ticket/api/controller/impl/DevController.java
> +        String newRefreshToken = jwtAuthTokenUtil.createRefreshToken( 7_200_000L);
필요없는 부분이라 삭제 진행했습니다.

2024-05-27 03:00 UTC, sam971114 commented on application/ticket-app-api/src/main/java/com/uket/app/ticket/api/service/AuthService.java
> +        tokenService.checkAndDeleteTokens(refreshToken);
deleteTokenIfExist로 수정 진행했습니다.

2024-05-27 03:01 UTC, sam971114 commented on domain/core-domain/src/main/generated/com/uket/domain/core/entity/QBaseEntity.java
해당 내용 수정 진행했습니다.

2024-05-27 03:03 UTC, sam971114 commented on modules/token-redis/src/main/java/com/uket/modules/redis/config/RedisConfig.java
> +    }
수정 진행했습니다.

2024-05-27 03:08 UTC, sam971114 commented on modules/token-redis/src/main/java/com/uket/modules/redis/properties/RedisProperties.java
> +    }
Record로 변경 완료했습니다.

2024-05-27 03:09 UTC, sam971114 commented on modules/token-redis/src/main/java/com/uket/modules/redis/service/TokenService.java
> +
넵넵

2024-05-27 03:09 UTC, sam971114 commented on modules/token-redis/src/main/java/com/uket/modules/redis/properties/RedisProperties.java
> +@Configuration
해당 내용 삭제했습니다.

2024-05-27 03:15 UTC, sam971114 commented on modules/jwt-provider/src/main/java/com/uket/modules/jwt/util/JwtAuthTokenUtil.java
> +                .claim(JwtValues.JWT_PAYLOAD_KEY_ID, uuid)
변경 완료했습니다.

2024-05-27 03:15 UTC, sam971114 commented on modules/jwt-provider/src/main/java/com/uket/modules/jwt/util/JwtAuthTokenUtil.java
> +                .claim(JwtValues.JWT_PAYLOAD_KEY_ID, uuid)
변경 완료했습니다.

2024-05-27 03:30 UTC, sam971114 commented on modules/token-redis/src/main/java/com/uket/modules/redis/service/TokenService.java
> +        tokenDetails.put("userId", userId.toString());
변경 완료했습니다.

2024-05-27 03:31 UTC, sam971114 commented on modules/token-redis/src/main/java/com/uket/modules/redis/service/TokenService.java
> +        //redisTemplate.expire(refreshTokenKey, Duration.ofSeconds(2));
해당 주석 삭제 진행했습니다.

2024-05-27 04:42 UTC, sam971114 commented on modules/token-redis/src/main/java/com/uket/modules/redis/service/TokenService.java
> +            throw new IllegalStateException("Refresh token is invalid or expired");
Custom 예외 처리 진행했습니다.

2024-05-27 05:36 UTC, sam971114 commented on modules/token-redis/src/main/java/com/uket/modules/redis/dto/RefreshTokenResponse.java
> +}
TokenResponse와 겹치는거 같아 삭제 진행했습니다.

2024-05-27 06:41 UTC, sam971114 commented on modules/token-redis/src/main/java/com/uket/modules/redis/service/TokenService.java
> +    }
내부에서 동작하도록 수정 완료했습니다.

2024-05-27 06:57 UTC, sam971114 commented on modules/token-redis/src/main/java/com/uket/modules/redis/service/TokenService.java
> +        }
해당 내용 수정 완료했습니다.

2024-05-27 07:00 UTC, sam971114 commented on modules/token-redis/src/main/java/com/uket/modules/redis/properties/RedisProperties.java
> +    private String password;
해당 내용 삭제 진행했습니다.

2024-05-27 07:17 UTC, sam971114 commented on modules/token-redis/src/main/java/com/uket/modules/redis/service/TokenService.java
> +public class TokenService {
혹시 RotateTokenService로 서비스명 변경해도 여전히 모호할까요??

2024-05-27 10:54 UTC, sam971114 commented on modules/token-redis/src/main/java/com/uket/modules/redis/service/TokenService.java
> +    }
AccessToken 확인 로직 및 예외처리 추가했습니다.

2024-05-27 11:00 UTC, sam971114 commented on modules/token-redis/src/main/java/com/uket/modules/redis/service/TokenService.java
> +
해당 내용 예외처리 완료했습니다.

2024-05-27 11:01 UTC, sam971114 commented on modules/token-redis/src/main/java/com/uket/modules/redis/service/TokenService.java
> +    }
내용 삭제 진행했습니다.

2024-05-28 00:44 UTC, 0703kyj commented on modules/token-redis/src/main/java/com/uket/modules/redis/service/TokenService.java
> +public class TokenService {
네 그럼 RotateTokenService로 바꾸면 괜찮을 것 같습니다~

2024-05-28 00:45 UTC, 0703kyj commented on domain/core-domain/src/main/generated/com/uket/domain/core/entity/QBaseEntity.java
현재 QType 클래스가 무시되도록 설정된 것은 확인했는데 이미 커밋된 QType 클래스는 여전히 남아있는 것 같아요..! github상에서 해당 클래스들 삭제가 필요해보입니다. 이것만 해결되면 합쳐도 될 것 같아요~

2024-05-29 02:17 UTC, 0703kyj commented on application/ticket-app-api/src/test/resources/application.yml
> +      maximum-pool-size: 40
이 설정이 왜 일로 온걸까요..?

2024-05-29 02:22 UTC, sam971114 commented on application/ticket-app-api/src/test/resources/application.yml
> +      maximum-pool-size: 40
merge충돌 일어나서 이전에 redis에 붙어있던 설정 옮긴건데 삭제 할까요..??

2024-05-29 02:25 UTC, sam971114 commented on application/ticket-app-api/src/test/resources/application.yml
> +      maximum-pool-size: 40
test코드에서 redis 설정 충돌한거 해결하다가 옮긴거같습니다. 다시 수정해두었습니다..

2024-05-29 02:49 UTC, 0703kyj approved these changes
진짜 고생많으셨습니다!! 합쳐도 될 것 같아요 :)

2024-05-29 03:03 UTC, merged