[SVR-15] 예매된 티켓 조회 기능
DCNJ-Uket/Uket-BE pull request #31
Opened 2024-06-04 02:53 UTC by sam971114

# 📌 개요
- 예매에 성공한 티켓을 조회하는 기능을 추가했습니다.

# 💻 작업사항
- CheckTicketDto를 통해 client가 티켓 확인에 필요한 내용들을 구성했습니다.
- 날짜에 offset을 더해 5월32일처럼 없는 날짜가 생성되는것을 수정했습니다.

# ❌ 주의사항
- N/A

# 💡 코드 리뷰 요청사항
- 필요한 정보가 모두 받아지는지 확인 부탁드립니다

2024-06-04 03:58 UTC, 0703kyj requested changes
고생하셨습니다! 조금 수정할 부분이 있는 것 같아서 코멘트 남겼습니다~ 확인 부탁드려요!

2024-06-04 03:58 UTC, 0703kyj commented on application/ticket-app-api/src/main/java/com/uket/app/ticket/api/controller/TicketApi.java
> +    @GetMapping("/all/{userId}")
해당 api path에 `/api/v1/tickets`가 포함되어 있는데 RESTful API에서 GET요청으로 엔드포인트를 복수형으로 두면 해당 값의 전체를 가져온다는 의미로 사용된다고 알고 있어요! 

https://github.com/osopromadze/Spring-Boot-Blog-REST-API 

여기 참고하면 좋을 것 같습니당. 그리고 사용자 티켓 조회는 사용자가 중심이 되어야 될 것 같은데 `TicketApi` 말고 `UserApi`에서 관리하도록 하는 건 어떨까요?
`GET /api/v1/users/tickets` 요런식으로 구성되어도 좋을 것 같아요! `userId` 같은 경우엔 `@LoginUserId` 어노테이션을 사용하면 굳이 path에서 받지 않아도 accessToken에서 자동으로 추출해서 사용할 수 있습니당

2024-06-04 03:58 UTC, 0703kyj commented on application/ticket-app-api/src/main/java/com/uket/app/ticket/api/controller/TicketApi.java
> +    );
저희 응답 주는 방식은 ResponseEntity를 사용하는 걸로 통일할게요! List로 응답이 필요한 경우에는 `dto/response` 패키지 안에 ListResponse있는데 그거 사용하면 좋을 것 같아용
```suggestion
    ResponseEntity<ListResponse<CheckTicketDto>> getUserTickets(
        @Parameter(description = "사용자 ID")
        @PathVariable Long userId
    );
```

2024-06-04 03:58 UTC, 0703kyj commented on application/ticket-app-api/src/main/java/com/uket/app/ticket/api/service/TicketingService.java
> +    }
유저의 모든 티켓을 가져오는 메서드인 것 같은데 `TicketingService`과는 관련없어 보여요..! 다른 클래스로 옮기는게 좋을 것 같습니당

그리고 `checkUserTickets`라는 메서드명이 잘 이해가 안되는 것 같아요. 단순히 티켓들을 조회하는 기능만 수행하고 Ticket을 체크하는 기능은 없는 것 같은데 혹시 이렇게 명명하신 이유가 있을까요?

```suggestion
    public List<CheckTicketDto> checkUserTickets(Long userId) {
        List<Ticket> tickets = ticketService.findAllTicketsByUserId(userId);
        
        return tickets.stream().map(CheckTicketDto::from).toList();
    }
```
이런 식으로 Stream을 사용해서 코드를 줄일 수도 있으니까 참고 부탁드려요~

2024-06-04 03:58 UTC, 0703kyj commented on domain/event-domain/src/main/java/com/uket/domain/event/repository/EventRepository.java
> +    Events findByName(String name);
`Events`의 `name`은 unique한 값이 아니라 `Events` 하나로 받으면 문제가 생길 수도 있을 것 같아요! `List<Events>` 로 받아 처리하는게 좋아보입니다~

2024-06-04 03:58 UTC, 0703kyj commented on domain/ticket-domain/src/main/java/com/uket/domain/ticket/dto/CheckTicketDto.java
> +        );
Builder 패턴 사용해서 반환하는게 좋아보여요! 인자값이 너무 많아서 순서가 바뀌기라도 할 경우에 문제가 생길 수 있어보입니당

2024-06-04 03:58 UTC, 0703kyj commented on domain/ticket-domain/src/main/java/com/uket/domain/ticket/dto/CheckTicketDto.java
> +        String showName = event.getName() + " " + show.getName();
이거 showName이 왜 event이름이랑 합쳐서 보내는건지 알 수 있을까요? figma살펴보니까 붙혀서 사용하는 것 같지는 않아서요!

2024-06-04 03:58 UTC, 0703kyj commented on domain/ticket-domain/src/main/java/com/uket/domain/ticket/entity/Ticket.java
> +    private String ticketSerialNumber;
erd상에서 해당 값은 `ticketNo`로 하기로 되어있어요! 둘 중 하나는 수정해주시면 감사하겠습니당. 그리고 이 값은 unique해야 해서 unique 제약 조건 거시는게 좋을 것 같아요! unique 거는 방식은 크게 2가지 있는걸로 알고 있는데 클래스 단에 `@Table` 어노테이션 사용해서 거는 방식으로 하는게 좋을 것 같습니다ㅎㅎ

2024-06-04 03:58 UTC, 0703kyj commented on domain/ticket-domain/src/main/java/com/uket/domain/ticket/entity/Ticket.java
> +import java.util.UUID;
19번줄이랑 20번줄은 사용되지 않는 의존성인 것 같습니당

2024-06-04 03:58 UTC, 0703kyj commented on domain/user-domain/src/main/java/com/uket/domain/user/repository/UserRepository.java
> +    Optional<Users> findByName(String name);
이것도 name자체가 unique한 속성이 아니에요..! 고려하셔서 방식 변경이 필요해보입니당

2024-06-04 03:58 UTC, 0703kyj commented on domain/user-domain/src/main/java/com/uket/domain/user/repository/UserRepository.java
> +    Optional<Users> findByName(String name);
살펴보니까 사용하지 않는 메서드인 것 같은데 지우는게 좋아보입니다~

2024-06-04 03:58 UTC, 0703kyj commented on domain/event-domain/src/main/java/com/uket/domain/event/repository/EventRepository.java
> +    Events findByName(String name);
이것도 사용하지 않는 메서드인 것 같네요!

2024-06-04 03:58 UTC, 0703kyj commented on domain/event-domain/src/main/java/com/uket/domain/event/repository/ReservationRepository.java
> +    List<Reservation> findByStartTime(LocalDateTime startTime);
사용하지 않는 메서드는 지워주세요~~

2024-06-04 03:58 UTC, 0703kyj commented on domain/event-domain/src/main/java/com/uket/domain/event/repository/ShowRepository.java
> +    List<Shows> findByName(String name);
사용하지 않는 메서드는 지워주세요~~

2024-06-04 04:46 UTC, 0703kyj commented on application/ticket-app-api/src/main/java/com/uket/app/ticket/api/controller/TicketApi.java
> +    @ApiResponse(responseCode = "200", description = "OK", content = @Content(array = @ArraySchema(schema = @Schema(implementation = CheckTicketDto.class))))
200응답은 클래스 단에 선언되어 있는데 다시 선언하신 이유가 있을까요?

2024-06-08 12:46 UTC, sam971114 commented on application/ticket-app-api/src/main/java/com/uket/app/ticket/api/controller/TicketApi.java
> +    @ApiResponse(responseCode = "200", description = "OK", content = @Content(array = @ArraySchema(schema = @Schema(implementation = CheckTicketDto.class))))
삭제했습니다!

2024-06-08 12:51 UTC, sam971114 commented on domain/ticket-domain/src/main/java/com/uket/domain/ticket/dto/CheckTicketDto.java
> +        String showName = event.getName() + " " + show.getName();
녹색지대 Day1 처럼 eventName과 showName의 합으로 보고 구현 진행했는데 혹시 figma 어디쪽 말씀하시는지 알 수 있을까요? 저는 2-1~2-3 확인하고 진행했습니다!

2024-06-08 12:57 UTC, sam971114 commented on application/ticket-app-api/src/main/java/com/uket/app/ticket/api/service/TicketingService.java
> +    }
userTicket들의 정보를 반환한다 생각해서 저렇게 지었습니다. 다른 이름 고려해보도록 하겠습니다.
또한 클래스 따로 만들어서 옮겨두도록 하겠습니다!

2024-06-08 13:43 UTC, 0703kyj commented on domain/ticket-domain/src/main/java/com/uket/domain/ticket/dto/CheckTicketDto.java
> +        String showName = event.getName() + " " + show.getName();
아 와이어 프레임보고 구현하신 것 같은데 그거 말고 디자인 파트 보면 따로 떨어져 있어요! 
그리고 이건 제 의견인데 데이터 전해줄 때는 가공하지 말고 원본으로 보내주고 프론트쪽에서 처리할 수 있게 하는게 추후 변경사항이 생기더라도 더 유연하게 사용할 수 있다고 생각합니다 😄

2024-06-09 03:13 UTC, sam971114 commented on domain/ticket-domain/src/main/java/com/uket/domain/ticket/dto/CheckTicketDto.java
> +        String showName = event.getName() + " " + show.getName();
확인했습니다. 그렇게 진행하도록  하겠습니다!

2024-06-10 01:35 UTC, 0703kyj commented on domain/ticket-domain/src/main/java/com/uket/domain/ticket/dto/CheckTicketDto.java
> +    String showName
여기서 구매일시도 같이 넘겨주면 좋을 것 같아요! Ticket의 createdAt 정보를 넘겨주면 좋을 것 같습니당

2024-06-11 05:08 UTC, 0703kyj approved these changes
고생하셨습니다!! 👍

2024-06-11 05:09 UTC, merged